### ISSUE TITLE
Crash on Start Up

### ISSUE THREAD

**Issue by Atlantispy** [SettingDust/lazyyyyy#7]
https://mclo.gs/aOvf449 - Crash Log

https://mclo.gs/8ZpBVWT - Latest Log

Fixes when I install Entity Sound Features, perhaps only apply the mixin if it's installed?

**Comment by SettingDust** [comment]
https://github.com/SettingDust/lazyyyyy/commit/5de07c20ffeb6475dbc71078baf944448ef9d186

https://github.com/SettingDust/lazyyyyy/issues/6#issuecomment-2502436003
