### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by damikdevil** [SettingDust/lazyyyyy#8]
on new versions of mod since 0.3.0 version game crashes when loading
[2024-11-26-1.log.gz](https://github.com/user-attachments/files/17930343/2024-11-26-1.log.gz)
[crash-2024-11-27_11.49.49-client.txt](https://github.com/user-attachments/files/17930345/crash-2024-11-27_11.49.49-client.txt)

**Comment by SettingDust** [comment]
Isn't fixed in the latest version 0.3.2?

**Comment by Zeykehasnt** [comment]
For me, it got fixed.
