### ISSUE TITLE
Incompatibility with Big Brain mod

### ISSUE THREAD

**Issue by YasonCore** [SettingDust/lazyyyyy#9]
After version 0.3.2 it incompatible with Big Brain

Mods: Big Brain, lazyyyyy, Forgified Fabric API, Kotlin for Forge

[latest.log](https://github.com/user-attachments/files/17995651/latest.log)

[crash-2024-12-03_20.48.55-client.txt](https://github.com/user-attachments/files/17995653/crash-2024-12-03_20.48.55-client.txt)

**Comment by SettingDust** [comment]
Fixed in dev. Need to fix the other bugs
